insert into `NATIONALITY`(`ID`,`CAPITAL`,`NAME`,`UPDATED_BY`,`UPDATED_ON`) values (1, 'ROMANIAN', 'BUCURESTI' , 'MIHALY' , '2020-04-01' );
insert into `NATIONALITY`(`ID`,`CAPITAL`,`NAME`,`UPDATED_BY`,`UPDATED_ON`) values (2, 'AMERICAN', 'WASHIGTON' , 'JOHN' , '2020-03-01' );
insert into `NATIONALITY`(`ID`,`CAPITAL`,`NAME`,`UPDATED_BY`,`UPDATED_ON`) values (3, 'HUNGARIAN', 'BUDAPESTA' , 'Evelyn' , '2020-03-01' );

